### ISSUE TITLE
Макеты

### ISSUE THREAD

**Issue by EdSergeev** [rambler-digital-solutions/rambler-it-android#7]
Макеты для iOS
![226615283_41118_17046897857458265756](https://cloud.githubusercontent.com/assets/3973026/18717899/41aa9b9a-802a-11e6-8b37-28881d027623.jpg)
![225517830_135701_11345365134555248835](https://cloud.githubusercontent.com/assets/3973026/18717911/44fb83c2-802a-11e6-8fa4-fca0922cf9b8.jpg)

**Comment by EdSergeev** [comment]
Макеты для iOS
![226615283_41118_17046897857458265756](https://cloud.githubusercontent.com/assets/3973026/18717899/41aa9b9a-802a-11e6-8b37-28881d027623.jpg)
![225517830_135701_11345365134555248835](https://cloud.githubusercontent.com/assets/3973026/18717911/44fb83c2-802a-11e6-8fa4-fca0922cf9b8.jpg)

**Comment by etolstoy** [comment]
Отпишите, кому нужно, дам доступ в Zeplin к полным макетам.

**Comment by katella** [comment]
@etolstoy Для начала мне (e.katella@rambler-co.ru), e.sergeev@rambler-co.ru и 
v.ibragimov@rambler-co.ru

**Comment by etolstoy** [comment]
Готово, выслал инвайты
